---
- hosts: 172.31.26.22
  become: yes
  tasks:
  - name: i want to execute linux commnd directly
    command: hostname 
    register: myresult
  - name: i want to disply myresult
    debug:
       msg: "{{myresult}}" 
  - name: i want to install git
    apt:
      name: git
      state: present
    when: myresult.stderr=="" 

  - name: i want to install tree
    apt:
      name:
    state: present
    when: myresult.stderr !=""           
    