---
- hosts: 172.31.26.22
  become: yes
  tasks:
  - name: install git
    apt: 
     name: tree
     state: present
     tags: mygit
- name: install wget
  apt:
    name: wget
    state: present
 
  
   